# fly.toml app configuration file generated for your Discord bot
app = 'replay-codes-bot'
primary_region = 'iad'

[build]

[env]
  PYTHONUNBUFFERED = "1"

[processes]
  app = "python bot.py"

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
